name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # run every 12 hours
  workflow_dispatch: # allow manual run

jobs:
  build:
    runs-on: ubuntu-latest

    # ðŸŸ¢ THIS FIXES THE PERMISSION ERROR
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          # Name of the GitHub user to generate the graph for
          github_user_name: ${{ github.repository_owner }}
          # List of files to generate
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
